# With this example, it is expected that there is a secret with the fulcio root & signing keys
# named 'fulcio-secret-rh' in namespace 'fulcio-system' and a secret 'rekor-private-key'
# with rekor signing keys in the 'rekor-system' namespace.
# secret names must match secret names in scaffold.tuf, that default to
# 'fulcio-secret-rh' and 'rekor-private-key'
# For root & key requirements, see ../requirements-keys-certs.md
# Note: User must substitute for localhost below.
---
configs:
  segment_backup_job:
    enabled: false
    namespace_create: false
  clientserver:
    consoleDownload: false
    route: false
  cosign_deploy:
    enabled: true
  fulcio:
    clusterMonitoring:
      enabled: false
    namespace_create: false
  rekor:
    clusterMonitoring:
      enabled: false
    namespace_create: false

# github.com/sigstore/helm-charts/charts
scaffold:
  fulcio:
    server:
      ingress:
        enabled: false
        http:
          enabled: false
    config:
      contents:
        OIDCIssuers:
          ? https://oauth2.sigstore.dev/auth
          : IssuerURL: https://oauth2.sigstore.dev/auth
            ClientID: sigstore
            Type: email
  rekor:
    server:
      ingress:
        enabled: false
        http:
          enabled: false
  tuf:
    ingress:
      create: false
