# With this example, it is expected that there is a secret with the fulcio root & signing keys
# named 'fulcio-secret-rh' in namespace 'fulcio-system' and a secret 'rekor-private-key'
# with rekor signing keys in the 'rekor-system' namespace.
# secret names must match secret names in scaffold.tuf, that default to
# 'fulcio-secret-rh' and 'rekor-private-key'
# For root & key requirements, see ../requirements-keys-certs.md
# Note: User must substitute for localhost below.
---
configs:
  clientserver:
    consoleDownload: false
    route: false
    # image:
    #   registry: quay.io
    #   repository: redhat-user-workloads/rhtas-tenant/access-1-0-gamma/client-server-1-0-gamma
  cosign_deploy:
    enabled: true
    # image:
    #   registry: quay.io
    #   repository: redhat-user-workloads/rhtas-tenant/cli-1-0-gamma/cosign-cli-2-2
  fulcio:
    clusterMonitoring:
      enabled: false
    namespace_create: false
  rekor:
    clusterMonitoring:
      enabled: false
    namespace_create: false
  rekorui:
    enabled: false
    route: false

# github.com/sigstore/helm-charts/charts
scaffold:
  # ctlog:
  #   server:
  #     image:
  #       registry: quay.io
  #       repository: redhat-user-workloads/rhtas-tenant/scaffold-1-0-gamma/ct-server-0-6
  #   createctconfig:
  #     image:
  #       registry: quay.io
  #       repository: redhat-user-workloads/rhtas-tenant/scaffold-1-0-gamma/createctconfig-0-6
  #   createtree:
  #     image:
  #       registry: quay.io
  #       repository: redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/createtree-0-6
  fulcio:
    # createcerts:
    #   image:
    #     registry: quay.io
    #     repository: redhat-user-workloads/rhtas-tenant/fulcio-1-0-gamma/createcerts-1-0-gamma
    server:
      # image:
      #   registry: quay.io
      #   repository: redhat-user-workloads/rhtas-tenant/fulcio-1-0-gamma/fulcio-1-0-gamma
      ingress:
        enabled: false
        http:
          enabled: false
    config:
      contents:
        OIDCIssuers:
          # https://<keycloak_instance>.<keycloak_ns>.<openshift_apps_subdomain>/auth/realms/sigstore
          ? http://keycloak-internal.keycloak-system.svc/auth/realms/sigstore
          : IssuerURL: http://keycloak-internal.keycloak-system.svc/auth/realms/sigstore
            ClientID: sigstore
            Type: email
  rekor:
    # redis:
    #   image:
    #     registry: quay.io
    #     repository: redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/redis-0-6
    server:
      # image:
      #   registry: quay.io
      #   repository: redhat-user-workloads/rhtas-tenant/rekor-1-0-gamma/rekor-server-1-0-gamma
      ingress:
        enabled: false
        http:
          enabled: false
  #   createtree:
  #     image:
  #       registry: quay.io
  #       repository: redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/createtree-0-6
  #   backfillredis:
  #     image:
  #       registry: quay.io
  #       repository: redhat-user-workloads/rhtas-tenant/rekor-1-0-gamma/backfill-redis-1-0-gamma
  # trillian:
  #   createdb:
  #     image:
  #       registry: quay.io
  #       repository: redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/createdb-0-6
  #   initContainerImage:
  #     netcat:
  #       registry: quay.io
  #       repository: redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/trillian-netcat-1-5
  #   redis:
  #     image:
  #       registry: quay.io
  #       repository: redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/redis-0-6

  #   logSigner:
  #     image:
  #       registry: quay.io
  #       repository: redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/trillian-logsigner-1-5
  #   logServer:
  #     image:
  #       registry: quay.io
  #       repository: redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/trillian-logserver-1-5
  #   mysql:
  #     image:
  #       registry: quay.io
  #       repository: redhat-user-workloads/rhtas-tenant/trillian-1-0-gamma/trillian-database-1-5
  tuf:
    ingress:
      create: false
    # deployment:
    #   registry: quay.io
    #   repository: redhat-user-workloads/rhtas-tenant/scaffold-1-0-gamma/tuf-server-0-6
