{{- range $configKey, $config := .Values.configs }}
{{- if and $config.clusterMonitoring (eq $config.clusterMonitoring.enabled true) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: {{ $config.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: {{ $config.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: {{ $config.namespace }}   
  name: {{ $config.namespace }}
  namespace: {{ $config.namespace }}
spec:
  endpoints:
  {{- range $endpoint := $config.clusterMonitoring.endpoints }}
  - interval: {{ $endpoint.interval }}
    port: {{ $endpoint.port }}
    scheme: {{ $endpoint.scheme }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: scaffolding
{{- end }}
{{- end }}