{{- range $configKey, $config := .Values.configs }}
{{- if $config.create }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $config.namespace }}
  {{- if and $config.clusterMonitoring (eq $config.clusterMonitoring.enabled true) }}
  labels:
    openshift.io/cluster-monitoring: "true"
  {{- end}}
{{- end }}
{{- end }}