kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
    - containerPath: /var/lib/kubelet/config.json
      # this is the path in gh action where the config is saved
      hostPath: /tmp/config.json
