{{- if .Values.configs.clientserver.consoleDownload }}
apiVersion: console.openshift.io/v1
kind: ConsoleCLIDownload
metadata:
  name: gitsign
spec:
  description: gitsign is a CLI tool that allows you to
    digitally sign and verify git commits.
  displayName: gitsign - Command Line Interface (CLI)
  links:
  - href: "https://{{ $.Values.configs.clientserver.name }}-{{ $.Values.configs.clientserver.namespace }}.{{ $.Values.global.appsSubdomain }}/clients/linux/gitsign"
    text: Download gitsign for Linux x86_64
  - href: "https://{{ $.Values.configs.clientserver.name }}-{{ $.Values.configs.clientserver.namespace }}.{{ $.Values.global.appsSubdomain }}/clients/darwin/gitsign"
    text: Download gitsign for Mac x86_64
  - href: "https://{{ $.Values.configs.clientserver.name }}-{{ $.Values.configs.clientserver.namespace }}.{{ $.Values.global.appsSubdomain }}/clients/windows/gitsign"
    text: Download gitsign for Windows x86_64
{{- end }}
