{{- if .Values.configs.clientserver.consoleDownload }}
apiVersion: console.openshift.io/v1
kind: ConsoleCLIDownload
metadata:
  name: rekor-cli
spec:
  description: rekor-cli is a CLI tool that allows you to
    interact with rekor server.
  displayName: rekor - Command Line Interface (CLI)
  links:
  - href: "https://{{ $.Values.configs.clientserver.name }}-{{ $.Values.configs.clientserver.namespace }}.{{ $.Values.global.appsSubdomain }}/clients/linux/rekor-cli"
    text: Download gitsign for Linux x86_64
  - href: "https://{{ $.Values.configs.clientserver.name }}-{{ $.Values.configs.clientserver.namespace }}.{{ $.Values.global.appsSubdomain }}/clients/darwin/rekor-cli"
    text: Download gitsign for Mac x86_64
  - href: "https://{{ $.Values.configs.clientserver.name }}-{{ $.Values.configs.clientserver.namespace }}.{{ $.Values.global.appsSubdomain }}/clients/windows/rekor-cli"
    text: Download gitsign for Windows x86_64
{{- end }}
