{{- if .Values.configs.clientserver.consoleDownload }}
apiVersion: console.openshift.io/v1
kind: ConsoleCLIDownload
metadata:
  name: cosign
spec:
  description: cosign is a CLI tool that allows you to
    manage sigstore artifacts.
  displayName: cosign - Command Line Interface (CLI)
  links:
  - href: "https://{{ $.Values.configs.clientserver.name }}-{{ $.Values.configs.clientserver.namespace }}.{{ $.Values.global.appsSubdomain }}/clients/linux/cosign"
    text: Download cosign for Linux x86_64
  - href: "https://{{ $.Values.configs.clientserver.name }}-{{ $.Values.configs.clientserver.namespace }}.{{ $.Values.global.appsSubdomain }}/clients/windows/cosign"
    text: Download cosign for Windows x86_64
  - href: "https://{{ $.Values.configs.clientserver.name }}-{{ $.Values.configs.clientserver.namespace }}.{{ $.Values.global.appsSubdomain }}/clients/darwin/cosign"
    text: Download cosign for Mac x86_64
{{- end }}
