{{- if .Values.configs.cosign_deploy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.configs.cosign_deploy.name }}
  namespace: {{ .Values.configs.cosign_deploy.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.configs.cosign_deploy.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.configs.cosign_deploy.name }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65533
      {{- if $.Values.configs.cosign_deploy.rolebindings }}
      serviceAccountName: {{ index .Values.configs.cosign_deploy.rolebindings 0 }}
      {{- end }}
      containers:
      - name: {{ .Values.configs.cosign_deploy.name }}
        image: "{{ template "image" .Values.configs.cosign_deploy.image }}"
        env:
        - name: OPENSHIFT_APPS_SUBDOMAIN
          value: {{ .Values.global.appsSubdomain }}
        - name: OIDC_AUTHENTICATION_REALM
          value: "trusted-artifact-signer"
        - name: COSIGN_OIDC_CLIENT_ID
          value: "trusted-artifact-signer"
        - name: COSIGN_FULCIO_URL
          value: "https://fulcio.$(OPENSHIFT_APPS_SUBDOMAIN)"
        - name: COSIGN_OIDC_ISSUER
          value: "https://keycloak-keycloak-system.$(OPENSHIFT_APPS_SUBDOMAIN)/auth/realms/$(OIDC_AUTHENTICATION_REALM)"
        - name: COSIGN_CERTIFICATE_OIDC_ISSUER
          value: "https://keycloak-keycloak-system.$(OPENSHIFT_APPS_SUBDOMAIN)/auth/realms/$(OIDC_AUTHENTICATION_REALM)"
        - name: COSIGN_REKOR_URL
          value: "https://rekor.$(OPENSHIFT_APPS_SUBDOMAIN)"
        - name: COSIGN_MIRROR
          value: "https://tuf.$(OPENSHIFT_APPS_SUBDOMAIN)"
        - name: COSIGN_ROOT
          value: "https://tuf.$(OPENSHIFT_APPS_SUBDOMAIN)/root.json"
        - name: COSIGN_YES
          value: "true"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
{{- end }}
