{{- if .Values.configs.cosign_deploy.enabled }}
{{- if .Values.configs.cosign_deploy.rolebindings }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.configs.cosign_deploy.namespace }}
  name: {{ index .Values.configs.cosign_deploy.rolebindings 0 }}
{{- end }}
{{- end }}
