{{- if .Values.configs.rekorui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.configs.rekorui.name }}
  namespace: {{ .Values.configs.rekorui.namespace }}
  labels:
    app: {{ .Values.configs.rekorui.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.configs.rekorui.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.configs.rekorui.name }}
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ .Values.configs.rekorui.name }}
      containers:
      - name: rekor-ui
        image: "{{ template "image" .Values.configs.rekorui.image }}"
        imagePullPolicy: Always
        env:
        - name: NEXT_PUBLIC_REKOR_DEFAULT_DOMAIN
          value: "https://rekor.{{ .Values.global.appsSubdomain }}"
        ports:
          - containerPort: 3000
            protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
{{- end }}
