{{- if .Values.configs.segment_backup_job.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.configs.segment_backup_job.name }}
  namespace: {{ .Values.configs.segment_backup_job.namespace }}
spec:
  schedule: "0 0 * * *"  
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 200
  suspend: false
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 3
  jobTemplate:                  
    spec:
      template:
          metadata:
            name: {{ .Values.configs.segment_backup_job.name }}
            labels:               
              parent: "segment-backup-job"
          spec:
            restartPolicy: OnFailure 
            serviceAccountName: segment-backup-job
            containers:
              - name: {{ .Values.configs.segment_backup_job.name }}
                # image: "{{ .Values.configs.segment_backup_job.image.registry }}/{{ .Values.configs.segment_backup_job.image.repository }}/{{ .Values.configs.segment_backup_job.image.version }}"
                image: "{{ .Values.configs.segment_backup_job.image.registry }}/{{ .Values.configs.segment_backup_job.image.repository }}@{{ .Values.configs.segment_backup_job.image.version }}"
                command: ["/bin/bash",  "/opt/app-root/src/script.sh"]
                env:
                  - name: RUN_TYPE
                    value: "nightly"
                securityContext:
                  allowPrivilegeEscalation: false
                  seccompProfile:
                    type: RuntimeDefault
                  capabilities:
                    drop:
                    - ALL
{{- end}}