{{- if .Values.configs.segment_backup_job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.configs.segment_backup_job.name }}
  namespace: {{ .Values.configs.segment_backup_job.namespace }}
spec:  
  parallelism: 1    
  completions: 1
  activeDeadlineSeconds: 600
  backoffLimit: 5
  template:
    metadata:
      name: {{ .Values.configs.segment_backup_job.name }}
      labels:               
        parent: "segment-backup-job"
    spec:
      restartPolicy: OnFailure 
      serviceAccountName: segment-backup-job
      containers:
        - name: {{ .Values.configs.segment_backup_job.name }}
          image: "{{ template "image" .Values.configs.segment_backup_job.image }}"
          command: ["/bin/bash",  "/opt/app-root/src/script.sh"]
          env:
            - name: RUN_TYPE
              value: "installation"
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
              - ALL
{{- end}}