{{- if .Values.configs.segment_backup_job.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: segment-backup-job
  namespace: {{ .Values.configs.segment_backup_job.namespace }}
secrets:
- name: pull-secret
{{- end}}