apiVersion: v1
kind: ServiceAccount
metadata:
  name: segment-backup-job
  # namespace: {{ .Values.configs.segment_backup_job.namespace }}
  namespace: trusted-artifact-signer-monitoring
secrets:
- name: pull-secret