{{ if .Values.configs.tas_initializer_job.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tas-initializer-rekor
  namespace: {{ .Values.configs.rekor.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tas-initializer
subjects:
- kind: ServiceAccount
  name: tas-initializer
  namespace: {{ .Values.configs.tas_initializer_job.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tas-initializer-fulcio
  namespace: {{ .Values.configs.fulcio.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tas-initializer
subjects:
- kind: ServiceAccount
  name: tas-initializer
  namespace: {{ .Values.configs.tas_initializer_job.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tas-initializer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tas-initializer
subjects:
- kind: ServiceAccount
  name: tas-initializer
  namespace: {{ .Values.configs.tas_initializer_job.namespace }}
{{- end }}
