{{- if and .Values.configs.tas_initializer_job.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: tas-initializer-input
  namespace: {{ .Values.configs.tas_initializer_job.namespace }}
type: Opaque
data:
  organization_name: {{ .Values.configs.tas_initializer_job.secret.organization_name | b64enc  }}
  email_address: {{ .Values.configs.tas_initializer_job.secret.email_address | b64enc  }}
  password: {{ .Values.configs.tas_initializer_job.secret.password | b64enc  }}
  fulcio_namespace: {{ .Values.configs.fulcio.namespace | b64enc }}
  fulcio_secret_name: {{ .Values.scaffold.fulcio.server.secret | b64enc }}
  rekor_namespace: {{ .Values.configs.rekor.namespace | b64enc  }}
  rekor_secret_name: {{ .Values.scaffold.rekor.server.signerFileSecretOptions.secretName | b64enc }}
{{- end}}
