{{ if .Values.configs.tas_initializer_job.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tas-initializer
  namespace: {{ .Values.configs.rekor.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tas-initializer
  namespace: {{ .Values.configs.fulcio.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tas-initializer
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - "config.openshift.io"
  resources:
  - "dnses"
  verbs:
  - get
  - list
{{- end }}
