---

# The private key values are for example/testing only - these are not sensitive nor are they used anywhere
configs:
  fulcio:
    server:
      secret:
        name: fulcio-secret-rh
        password: "secure"
        public_key_file: "keys-cert/file_ca_pub.pem"
        private_key_file: "keys-cert/file_ca_key.pem"
        root_cert_file: "keys-cert/fulcio-root.pem"
  rekor:
    signer:
      secret:
        name: rekor-private-key
        private_key_file: "keys-cert/rekor_key.pem"

scaffold:
  ctlog:
    namespace:
      create: false
    createctconfig:
      backoffLimit: 30
      enabled: true
      initContainerImage:
        curl:
          registry: registry.access.redhat.com
          repository: ubi9/ubi-minimal
          version: latest
          imagePullPolicy: IfNotPresent
  fulcio:
    namespace:
      name: fulcio-system
      create: false
    createcerts:
      enabled: true
    server:
      secret: fulcio-secret-rh
      ingress:
        http:
          enabled: true
          className: ""
          annotations:
            route.openshift.io/termination: "edge"
          hosts:
          - host: fulcio.apps.rosa.p9esn-qgkm3-wkk.o7au.p3.openshiftapps.com
            path: /
    config:
      contents:
        OIDCIssuers:
          # https://<keycloak_instance>.<keycloak_ns>.<base_domain>/auth/realms/sigstore
          ? https://keycloak-keycloak-system.apps.rosa.p9esn-qgkm3-wkk.o7au.p3.openshiftapps.com/auth/realms/sigstore
          : IssuerURL: https://keycloak-keycloak-system.apps.rosa.p9esn-qgkm3-wkk.o7au.p3.openshiftapps.com/auth/realms/sigstore
            ClientID: sigstore
            Type: email

  rekor:
    namespace:
      namespace: rekor-system
      create: false
    server:
      signer: /key/private
      signerFileSecretOptions:
        secretName: rekor-private-key
        secretMountPath: /key
        secretMountSubPath: private
        privateKeySecretKey: private
      ingress:
        className: ""
        annotations:
          route.openshift.io/termination: "edge"
        hosts:
          - host: rekor.apps.rosa.p9esn-qgkm3-wkk.o7au.p3.openshiftapps.com
            path: /
          
  trillian:
    namespace:
      create: false
    createdb:
    initContainerImage:
      netcat:
        registry: quay.io
        repository: securesign/netcat
        version: v1.0.0
      curl:
        registry: registry.access.redhat.com
        repository: ubi9/ubi-minimal
        version: latest
        imagePullPolicy: IfNotPresent
    redis:
      args:
        - /usr/bin/run-redis
        - --bind
        - 0.0.0.0
        - --appendonly
        - "yes"
      image:
        registry: registry.redhat.io
        repository: rhel9/redis-6
        version: "sha256:031a5a63611e1e6a9fec47492a32347417263b79ad3b63bcee72fc7d02d64c94"
        pullPolicy: IfNotPresent
        version: latest

  tuf:
    namespace:
      create: false
    secrets:
      fulcio:
        name: fulcio-secret-rh
    enabled: true
    ingress:
      className: ""
      annotations:
        route.openshift.io/termination: "edge"
      http:
        hosts:
          - host: tuf.apps.rosa.p9esn-qgkm3-wkk.o7au.p3.openshiftapps.com
            path: /
    deployment:
      registry: quay.io
      repository: ablock/tuf-server
      version: "sha256:c4f534807b331e97b107d908b7e0cf14a896399bc372bca6a2c7e4f6d730807c"

  copySecretJob:
    enabled: true
    backoffLimit: 1000
