annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: support
      url: https://github.com/securesign/sigstore-ocp/issues
    - name: Chart Source
      url: https://github.com/securesign/sigstore-ocp
    - name: Default Image Source
      url: ""
  charts.openshift.io/name: KeycloakOperator
  charts.openshift.io/provider: TrustedArtifactSigner
  charts.openshift.io/supportURL: https://github.com/securesign/sigstore-ocp/issues
apiVersion: v2
name: keycloak-operator
description: A Helm chart for deploying the Keycloak Operator Using the Operator Lifecycle Manager (OLM)
type: application
keywords:
  - operator
  - keycloak
kubeVersion: ">= 1.19.0-0"
maintainers:
  - name: TrustedArtifactSigner
    url: ""
sources:
  - https://github.com/securesign/sigstore-ocp
version: 0.1.0
