apiVersion: v2
name: scaffold
description: A Helm chart for deploying a Sigstore application opinionated for OpenShift

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0

dependencies:
  - name: fulcio
    version: 2.2.0
    repository: https://sigstore.github.io/helm-charts
    condition: fulcio.enabled
  - name: rekor
    version: 1.3.1
    repository: https://sigstore.github.io/helm-charts
    condition: rekor.enabled
  - name: trillian
    version: 0.2.2
    repository: https://sigstore.github.io/helm-charts
    condition: trillian.enabled
  - name: ctlog
    version: 0.2.40
    repository: https://sigstore.github.io/helm-charts
    condition: ctlog.enabled
  - name: tuf
    version: 0.1.4
    repository: https://sigstore.github.io/helm-charts
    condition: tuf.enabled
  - name: tsa
    version: 0.1.0
    repository: https://sigstore.github.io/helm-charts
    condition: tsa.enabled

annotations:
  artifacthub.io/license: Apache-2.0
