{{- if and .Values.configs.rekor.signer.secret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configs.rekor.signer.secret.name }}
  namespace: {{ .Values.configs.rekor.namespace }}
type: Opaque
stringData:
{{- if or .Values.configs.rekor.signer.secret.private_key .Values.configs.rekor.signer.secret.private_key_file }}
  private: {{ (.Values.configs.rekor.signer.secret.private_key | default .Values.configs.rekor.signer.secret.private_key (.Files.Get .Values.configs.rekor.signer.secret.private_key_file))  | toYaml | indent 2 }}
{{- end }}
{{- end }}