global:
  # -- DNS name to generate environment variables and consoleCLIDownload urls.
  # By default, in OpenShift, the value for this is
  # apps.$(oc get dns cluster -o jsonpath='{ .spec.baseDomain }')
  appsSubdomain: ""

configs:
  clientserver:
    # -- Whether to create the OpenShift resource 'ConsoleCLIDownload' for each binary.
    # -- This can only be enabled if the OpenShift CRD is registered.
    consoleDownload: true
    # -- Whether to create the OpenShift route resource
    route: true
    name: tas-clients
    namespace_create: true
    namespace: trusted-artifact-signer-clientserver
    image:
      registry: registry.redhat.io
      repository: rhtas/client-server
      version: "sha256:cceba85b20e391029aab2d9980c825fd653bc8b5223d09667e0ef0b27137a430"
      pullPolicy: IfNotPresent
  ctlog:
    namespace: ctlog-system
    namespace_create: true
    # -- Names for rolebindings to add clusterroles to ctlog serviceaccounts.
    # The names must match the serviceaccount names in the ctlog namespace.
    rolebindings:
      - ctlog
      - ctlog-createtree
      - trusted-artifact-signer-ctlog-createctconfig

  rekor:
    namespace_create: true
    namespace: rekor-system
    # -- names for rolebindings to add clusterroles to rekor serviceaccounts.
    # The names must match the serviceaccount names in the rekor namespace.
    rolebindings:
      - rekor-redis
      - rekor-server
      - trusted-artifact-signer-rekor-createtree
    # -- Signer holds secret that contains the private key used to sign entries and the tree head of the transparency log
    # When this section is left out, scaffold.rekor creates the secret and key.
    signer:
      secret:
        # -- Name of the secret to create with the private key data. This name must match the value in
        # scaffold.rekor.server.signer.signerFileSecretOptions.secretName.
        name: ""
        # -- Private encrypted signing key
        private_key: ""
        # -- File containing a private encrypted signing key
        private_key_file: ""
    #  -- With ClusterMonitoring enabled, a ServiceMonitor and RBAC is created. This adds a  metrics target from rekor-server
    #  in the openshift-monitoring namespace scraped by prometheus along with other cluster-monitoring targets.
    clusterMonitoring:
      enabled: true
      endpoints:
        - interval: 30s
          port: 2112-tcp
          scheme: http

  fulcio:
    namespace_create: true
    namespace: fulcio-system
    # -- Names for rolebindings to add clusterroles to fulcio serviceaccounts.
    # The names must match the serviceaccount names in the fulcio namespace.
    rolebindings:
      - fulcio-createcerts
      - fulcio-server
    server:
      #  -- Secret to create with fulcio signing backend certificate and keys.
      #  Leave this section out if a secret already exists in the fulcio namespace.
      #  The secret.name must match the value of scaffold.fulcio.server.secret and
      #  also tuf.secrets.fulcio.name. For details on certificate and key requirements,
      #  see https://github.com/sigstore/fulcio/blob/main/docs/setup.md#ca-certificate-requirements
      secret:
        name: ""
        # -- password to decrypt the signing key
        password: ""
        # -- signer public key
        public_key: ""
        # -- a PEM-encoded encrypted signing key
        private_key: ""
        # -- file containing signer public key
        public_key_file: ""
        # -- file containing a PEM-encoded encrypted signing key
        private_key_file: ""
        # -- fulcio root certificate authority (CA)
        root_cert: ""
        # -- file containing fulcio root certificate authority (CA)
        root_cert_file: ""
    #  -- With ClusterMonitoring enabled, a ServiceMonitor and RBAC is created. This adds a  metrics target from fulcio-server
    #  in the openshift-monitoring namespace scraped by prometheus along with other cluster-monitoring targets.
    clusterMonitoring:
      enabled: true
      endpoints:
        - interval: 30s
          port: 2112-tcp
          scheme: http

  trillian:
    namespace_create: true
    namespace: trillian-system
    # -- names for rolebindings to add clusterroles to trillian serviceaccounts.
    # The names must match the serviceaccount names in the trillian namespace.
    rolebindings:
      - trillian-logserver
      - trillian-logsigner
      - trillian-mysql

  tuf:
    namespace: tuf-system
    namespace_create: true
    # -- names for rolebindings to add clusterroles to tuf serviceaccounts.
    # The names must match the serviceaccount names in the tuf namespace.
    rolebindings:
      - tuf
      - tuf-secret-copy-job

  cosign_deploy:
    enabled: false
    namespace: cosign
    namespace_create: true
    # -- names for rolebindings to add clusterroles to cosign serviceaccounts.
    # The names must match the serviceaccount names in the cosign namespace.
    rolebindings:
      - cosign
    # -- Name of deployment
    name: cosign
    # -- Image containing the cosign binary as well as environment variables with the base domain injected.
    image:
      registry: registry.redhat.io
      # TODO: update image
      repository: securesign/cosign
      version: v2.1.1
      pullPolicy: IfNotPresent

rbac:
  # -- clusterrole to be added to sigstore component serviceaccounts.
  clusterrole: system:openshift:scc:anyuid

# github.com/sigstore/helm-charts/charts
scaffold:
  ctlog:
    enabled: true
    forceNamespace: ctlog-system
    fullnameOverride: ctlog
    namespace:
      create: false
      name: ctlog-system
    server:
      image:
        registry: registry.redhat.io
        repository: rhtas/ct-server
        version: "sha256:8c8c5086971da312b586f19392ee60ce2436e9dac36888d71bcacf2ead76a433"
        pullPolicy: IfNotPresent
    createctconfig:
      backoffLimit: 30
      enabled: true
      initContainerImage:
        curl:
          registry: registry.access.redhat.com
          repository: ubi9/ubi-minimal
          version: latest
          imagePullPolicy: IfNotPresent
      image:
        registry: registry.redhat.io
        repository: rhtas/createctconfig
        version: "sha256:98e890808eaf8e19fbdfaf486f17ae6b75a7a7d4948fea6b99dea69438fa254a"
        pullPolicy: IfNotPresent
    createcerts:
      fullnameOverride: ctlog-createcerts
    createtree:
      fullnameOverride: ctlog-createtree
      displayName: ctlog-tree
      image:
        registry: registry.redhat.io
        repository: rhtas/createtree
        version: "sha256:4886b6f9295cbc48f36c7545759abeba9de4a67135a128f71a7bb673ef672925"
        pullPolicy: IfNotPresent
  fulcio:
    enabled: true
    forceNamespace: fulcio-system
    ctlog:
      enabled: false
      createctconfig:
        logPrefix: sigstorescaffolding
    namespace:
      name: fulcio-system
      create: false
    createcerts:
      enabled: false
      fullnameOverride: fulcio-createcerts
      image:
        registry: registry.redhat.io
        repository: rhtas/createcerts
        version: "sha256:29554896f547ccca06b46e67053b5ae65e340cd87617aa19dd2668dbf259c171"
        pullPolicy: IfNotPresent
    server:
      fullnameOverride: fulcio-server
      image:
        registry: registry.redhat.io
        repository: rhtas/fulcio
        version: "sha256:04e6ba8bb0042596d70abe2162def7ebc4acc96c03ec0fcc090a32c1478f1fec"
        pullPolicy: IfNotPresent
      # If content and/or files not provided in configs.fulcio.secret
      # then this secret must exist in fulcio-system ns. See ../quickstart-with-keycloak.md
      # for how to create this secret.
      secret: fulcio-secret-rh
      ingress:
        http:
          enabled: true
          className: ""
          annotations:
            route.openshift.io/termination: "edge"
          hosts:
          - host: fulcio.appsSubdomain
            path: /

  rekor:
    enabled: true
    forceNamespace: rekor-system
    fullnameOverride: rekor
    namespace:
      name: rekor-system
      create: false
    trillian:
      enabled: false
    redis:
      fullnameOverride: rekor-redis
    server:
      fullnameOverride: rekor-server
      image:
        registry: registry.redhat.io
        # TODO: update image
        repository: rhtas/rekor-server
        version: "sha256:885cef3238f56eb72410afd5b409e6c4e0d8003e8548314957fb7a555c1507fb"
        pullPolicy: IfNotPresent
      # when providing contents of secret with configs.rekor.signer
      # the signer sections must also be provided here
      signer: /key/private
      signerFileSecretOptions:
        secretName: rekor-private-key
        secretMountPath: /key
        secretMountSubPath: private
        privateKeySecretKey: private
      ingress:
        className: ""
        annotations:
          route.openshift.io/termination: "edge"
        hosts:
          - host: rekor.appsSubdomain
            path: /

    createtree:
      image:
        registry: registry.redhat.io
        repository: rhtas/createtree
        version: "sha256:4886b6f9295cbc48f36c7545759abeba9de4a67135a128f71a7bb673ef672925"
        pullPolicy: IfNotPresent
    backfillredis:
      image:
        registry: registry.redhat.io
        repository: rhtas/backfill-redis
        version: "sha256:da72f5aa5684061d43f9a8c9d2662b0b9c46c29db87697b933c512d0ef8c6e71"
        pullPolicy: IfNotPresent
  trillian:
    enabled: true
    forceNamespace: trillian-system
    fullnameOverride: trillian
    namespace:
      create: false
      name: trillian-system
    createdb:
      image:
        registry: registry.redhat.io
        repository: rhtas/createdb
        version: "sha256:e2378132bf8a3043a54b9d49d77ba7b5ad1d2f922ae2998c10f94cabc5b99207"
        pullPolicy: IfNotPresent
    initContainerImage:
      netcat:
        registry: registry.redhat.io
        repository: rhtas/trillian-netcat
        version: "sha256:f293c516c46a68114c8400c6ac67b043a37efc1c3fb6e29198cffef6b92b47c6"
      curl:
        registry: registry.access.redhat.com
        repository: ubi9/ubi-minimal
        version: latest
        imagePullPolicy: IfNotPresent
    redis:
      args:
        - /usr/bin/run-redis
        - --bind
        - 0.0.0.0
        - --appendonly
        - "yes"
      image:
        registry: registry.redhat.io
        repository: rhel9/redis-6
        version: "sha256:031a5a63611e1e6a9fec47492a32347417263b79ad3b63bcee72fc7d02d64c94"
        pullPolicy: IfNotPresent

    logSigner:
      name: trillian-logsigner
      fullnameOverride: trillian-logsigner
      image:
        registry: registry.redhat.io
        repository: rhtas/trillian-logsigner
        version: "sha256:715a2138d3bf81620c1d9fb6d5533c6b535bfaa7a1e63af74a525d4334851292"
        pullPolicy: IfNotPresent
    logServer:
      name: trillian-logserver
      fullnameOverride: trillian-logserver
      portHTTP: 8090
      portRPC: 8091
      image:
        registry: registry.redhat.io
        repository: rhtas/trillian-logserver
        version: "sha256:de6ced024e6f3d6d9ba8aaf344dde9d947017090953a35d30ab158e9a55d7e93"
        pullPolicy: IfNotPresent
    mysql:
      fullnameOverride: trillian-mysql
      gcp:
        scaffoldSQLProxy:
          registry: registry.redhat.io
          repository: rhtas/cloudsqlproxy
          version: "sha256:0c5cb89d56890d3a8349799eb543630268a8fbc21789aa6bd4a99c981865e89a"
      image:
        registry: registry.redhat.io
        repository: rhtas/trillian-database
        version: "sha256:648264a29b005d57b3b0b967f42b16f7c4767cc2d5d11d899c562f6b08a31573"
        pullPolicy: IfNotPresent
      args: []
      securityContext:
        fsGroup: 0
      livenessProbe:
        exec:
          command:
          - mysqladmin
          - ping
          - -h
          - localhost
          - -u
          - $(MYSQL_USER)
          - -p$(MYSQL_PASSWORD)
      readinessProbe:
        exec:
          command:
          - mysqladmin
          - ping
          - -h
          - localhost
          - -u
          - $(MYSQL_USER)
          - -p$(MYSQL_PASSWORD)
  tuf:
    namespace:
      create: false
      name: tuf-system
    forceNamespace: tuf-system
    fullnameOverride: tuf
    secrets:
      fulcio:
        name: fulcio-secret-rh
        path: fulcio-cert
      rekor:
        name: rekor-public-key
        path: rekor-pubkey
      ctlog:
        name: ctlog-public-key
        path: ctfe.pub

    enabled: true
    ingress:
      className: ""
      annotations:
        route.openshift.io/termination: "edge"
      http:
        hosts:
          - host: tuf.appsSubdomain
            path: /
    deployment:
      registry: registry.redhat.io
      repository: rhtas/tuf-server
      version: "sha256:0f7eacf4605a6d82ace28d8b3d2479b698585e89c46af94a8319fd309ee83dc0"

  copySecretJob:
    name: copy-secrets-job
    enabled: true
    registry: registry.redhat.io
    repository: openshift4/ose-cli
    version: latest
    imagePullPolicy: IfNotPresent
    serviceaccount: tuf-secret-copy-job
    backoffLimit: 1000

  tsa:
    enabled: false
    forceNamespace: tsa-system
    namespace:
      create: false
      name: tsa-system
    server:
      fullnameOverride: tsa-server
