# This serviceaccount is an example that will create identity tokens
# in pods/namespaces using this serviceaccount if the ROSA cluster is configured with STS
{{- if .Values.signingNamespace.enabled }} {{ if .Values.signingIdentity.rosa.sts.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rosa.sts.serviceaccount }}
  namespace: {{ .Values.signingNamespace | quote }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.rosa.sts.roleArn }}
    # optional: Defaults to "sigstore" if not set
    eks.amazonaws.com/audience: {{ .Values.rosa.sts.audience }}
    # optional: When set to "true", adds AWS_STS_REGIONAL_ENDPOINTS env var
    #   to containers
    eks.amazonaws.com/sts-regional-endpoints: {{ .Values.rosa.sts.regionalEndpoints }}
    # optional: Defaults to 86400 for expirationSeconds if not set
    #   Note: This value can be overwritten if specified in the pod
    #         annotation as shown in the next step.
    eks.amazonaws.com/token-expiration: {{ .Values.rosa.sts.expiration }}
{{- end }}
