name: Lint Charts

on:
  pull_request:
    paths:
      - "charts/**"

jobs:
  check-metadata:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4
        with:
          python-version: 3.7

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version: ^1

      - name: Setup helm-docs
        run: go install github.com/norwoodj/helm-docs/cmd/helm-docs@latest

      - name: Run pre-commit
        uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # renovate: tag=v3.0.0
        with:
          extra_args: --show-diff-on-failure
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # renovate: tag=v3.5
        with:
          version: v3.12.3

      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@e8788873172cb653a90ca2e819d79d65a66d4e76 # renovate: tag=v2.4.0

      - name: "Add Sigstore Repository"
        run: |
          helm repo add sigstore "https://sigstore.github.io/helm-charts"
          helm repo update

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml

      #- name: Create KIND Cluster
      #  uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140 # v1.8.0

      #- name: Run chart-testing (install)
      #  run: ct install --config ct-install.yaml
